/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The result of a Cypher query: a list of column names and a list of rows.
 *
 * Each row is an object mapping column name to its value.  Value types: `null`,
 * `number`, `boolean`, `string`, `{ $type: "node", id: string }`,
 * `{ $type: "edge", id: string }`.
 *
 * ```typescript
 * interface QueryResult {
 *   columns: string[];
 *   rows: Record<string, unknown>[];
 * }
 * ```
 */
export interface QueryResult {
  /** Ordered list of column names returned by the query. */
  columns: Array<string>
  /** One element per result row; each row maps column name to its value. */
  rows: Array<any>
}
/**
 * A single result row from a vector or full-text search.
 *
 * ```typescript
 * interface NodeResult {
 *   // Node ID as a decimal string (full u64 range, JS-safe).
 *   id: string;
 *   // Relevance score: cosine similarity / BM25 score / distance.
 *   score: number;
 * }
 * ```
 */
export interface NodeResult {
  /** Node ID as a decimal string to preserve u64 precision across the JS boundary. */
  id: string
  /** Relevance score widened to f64 for JS compatibility. */
  score: number
}
/**
 * Coverage report for an HNSW index — see `SparrowDB.vectorIndexHealth`.
 *
 * ```typescript
 * interface VectorIndexHealth {
 *   stored: number;       // vectors stored in the index
 *   reachable: number;    // vectors `vectorSearch` can actually reach
 *   unreachable: number;  // stored - reachable; must be 0 when healthy
 * }
 * ```
 *
 * Note the `//` comments above rather than nested doc comments. A JSDoc
 * close-marker inside a generated JSDoc block terminates it early, and every
 * declaration after that point is then parsed as code — which is exactly how
 * the checked-in `npm/sparrowdb/index.d.ts` stopped parsing as TypeScript
 * (#449). `npm run typecheck` in CI now guards against a recurrence; keep
 * examples in these doc comments to `//` so it never fires.
 */
export interface VectorIndexHealth {
  /** Vectors stored in the index. */
  stored: number
  /** Vectors reachable by greedy traversal from the entry point. */
  reachable: number
  /** `stored - reachable`. Non-zero means silent recall loss. */
  unreachable: number
}
/**
 * One damaged HNSW index file — see `SparrowDB.vectorIndexLoadFailures`.
 *
 * ```typescript
 * interface VectorIndexLoadFailure {
 *   label: string;   // node label the index was built on
 *   prop: string;    // vector property the index was built on
 *   path: string;    // exact file on disk; the machine-readable field
 *   reason: string;  // human-readable; see the caveat below
 * }
 * ```
 *
 * `path` is exact and is the field to key alerts and remediation on. `reason`
 * is a message for a human to read: for a quarantine artifact it is
 * RECONSTRUCTED rather than recovered, because #442 reports the original
 * decode failure only in the error it returns at quarantine time and writes no
 * sidecar. Do not parse it and do not present it as the authoritative cause.
 *
 * The `//` comments above are deliberate rather than nested doc comments: a
 * close-comment marker inside a generated JSDoc block ends it early, which is
 * part of why the checked-in `npm/sparrowdb/index.d.ts` does not currently
 * parse as TypeScript (issue #449).
 */
export interface VectorIndexLoadFailure {
  /** Node label the damaged index was built on. */
  label: string
  /** Vector property the damaged index was built on. */
  prop: string
  /**
   * Exact path of the damaged bytes on disk — live `.bin` or
   * `.bin.corrupt.<millis>` quarantine artifact.
   */
  path: string
  /**
   * Human-readable description. Reconstructed for quarantine artifacts;
   * not authoritative and not machine-parseable.
   */
  reason: string
}
/**
 * What an inspection of a database's `vector_indexes/` observed — see
 * `SparrowDB.vectorIndexLoadFailures` and `SparrowDB.vectorIndexDamageScan`.
 *
 * ```typescript
 * interface VectorIndexDamageReport {
 *   unscannable?: string;                  // present when the directory could not be listed
 *   active: VectorIndexLoadFailure[];      // unrecovered damage — alert on this
 *   historical: VectorIndexLoadFailure[];  // recovered-from damage — forensics only
 *   healthy: boolean;                      // !unscannable && active.length === 0
 * }
 * ```
 *
 * Not to be confused with the instance method `db.vectorIndexHealth(label,
 * prop)`, which returns per-index vector reachability counts. This type is
 * about which index FILES are in service; that one is about how many vectors
 * inside one healthy file a search can reach.
 *
 * Three fields, because a report has three things to say (#456). Before #456
 * this was a bare `VectorIndexLoadFailure[]`, and `[]` meant all three at once:
 *
 * - `unscannable` — `[]` also meant "I could not read the directory". A
 *   `chmod 000` on `vector_indexes/`, a bad mount during a poll, or a
 *   misconfigured service account produced output byte-identical to a healthy
 *   store, so a monitor could not tell green from blind. When this is non-null,
 *   `active` and `historical` are empty FOR LACK OF OBSERVATION, not lack of
 *   damage. Check it before concluding anything.
 * - `historical` — a quarantine artifact whose `(label, prop)` is served again
 *   by a working index. It used to stay in the one array forever, because #442
 *   never cleans artifacts up, so a repaired store could go green to red and
 *   never back. An alert that will not clear after the problem is fixed gets
 *   muted, and a muted alert is worse than none. Reported rather than
 *   suppressed because #442 records no reason at quarantine time and writes no
 *   sidecar: the artifact file is the only surviving evidence of the incident.
 * - `healthy` — computed natively as `!unscannable && active.length === 0`, so
 *   a caller cannot get the composition wrong. An unscannable report is NOT
 *   healthy: not knowing is not the same as being fine.
 */
export interface VectorIndexDamageReport {
  /**
   * Present when `vector_indexes/` could not be listed; the string says why.
   * ABSENT (not null) when the scan succeeded — the native layer omits the
   * property rather than setting it, so test it for truthiness.
   *
   * While set, `active` and `historical` are empty because nothing was
   * observed — not because nothing is wrong.
   */
  unscannable?: string
  /**
   * Damage that is still unrecovered. The vectors for these pairs are not in
   * service and writes to them are being dropped. This is the alert.
   */
  active: Array<VectorIndexLoadFailure>
  /**
   * Quarantine artifacts whose `(label, prop)` a working index now serves.
   * Forensics for an operator; a monitor ignores this.
   */
  historical: Array<VectorIndexLoadFailure>
  /** `!unscannable && active.length === 0`. Computed natively. */
  healthy: boolean
}
/**
 * Top-level database handle.
 *
 * ```typescript
 * import { SparrowDB } from 'sparrowdb'
 *
 * const db = SparrowDB.open('/path/to/my.db')
 * const result = db.execute('MATCH (n:Person) RETURN n.name LIMIT 5')
 * for (const row of result.rows) {
 *   console.log(row['n.name'])
 * }
 * db.checkpoint()
 * ```
 */
export declare class SparrowDB {
  /**
   * Open (or create) a SparrowDB database at `path`.
   *
   * Throws if the path cannot be created or the database files are corrupt.
   */
  static open(path: string): SparrowDB
  /**
   * Deep damage report for the vector indexes at `path`: reads and validates
   * every live index file.
   *
   * **Static**, and deliberately so: the database this diagnoses is usually
   * one that will not open. `open` fails with a `Corruption` error when a
   * live index file cannot be loaded, and this is the call that answers
   * *which* files caused it — so requiring an instance would make it
   * unreachable in the exact situation it exists for.
   *
   * **Never throws.** There is no configuration of the filesystem that turns
   * the diagnostic itself into a second failure to diagnose. A directory it
   * cannot list is reported in `unscannable` rather than raised.
   *
   * **Not for a poll loop.** This deserialises every HEALTHY index it finds —
   * for an 8 MB `Knowledge.embedding` index polled hourly, 8 MB of I/O and a
   * complete HNSW graph rebuild an hour, spent confirming that nothing is
   * wrong. Use `SparrowDB.vectorIndexDamageScan` for monitoring and this for
   * "why will my database not open?".
   *
   * Damage is reported in both places it can live:
   *
   * - **live but not serving** — `hnsw_<label>_<prop>.bin` is present and
   *   either does not resolve or does not load; `open` fails on these;
   * - **already quarantined** — `hnsw_<label>_<prop>.bin.corrupt.<millis>`,
   *   bytes a previous load attempt moved aside (#442).
   *
   * The second arm is why this is the only usable health signal for #451:
   * once a damaged file has been quarantined, the *first* `open` has already
   * thrown and every later `open` succeeds with the index silently absent,
   * so vector writes for that pair are dropped and searches return nothing.
   * Nothing else distinguishes that store from a healthy one.
   *
   * **Read-only since #456.** It used to quarantine the live entries it
   * probed, so a second call answered differently from the first and the
   * `path` it reported had already been renamed away by the time you read it.
   * Both are fixed: run it as often as you like, and `path` resolves.
   *
   * ```typescript
   * const report = SparrowDB.vectorIndexLoadFailures('/path/to/my.db')
   * if (report.unscannable) throw new Error(`cannot inspect: ${report.unscannable}`)
   * if (!report.healthy) alert(report.active.map(f => f.path))
   * // report.historical — damage already recovered from; do not alert
   * ```
   */
  static vectorIndexLoadFailures(path: string): VectorIndexDamageReport
  /**
   * Cheap damage report for the vector indexes at `path`: directory metadata
   * only, no index file contents read.
   *
   * **This is the call for a monitor.** Its cost is one directory listing plus
   * one `stat` per live index, independent of index size, so it is safe at any
   * poll frequency. `SparrowDB.vectorIndexLoadFailures` is the deep
   * counterpart and deserialises every healthy index on every call.
   *
   * **Static** and **never throws**, for the same reasons.
   *
   * What it sees: quarantine artifacts, split into `active` and `historical`
   * by whether a live index now serves the pair, and live entries that do not
   * resolve. What it does not: whether a live index still DECODES.
   *
   * That is sound for a RUNNING store, and the reason is structural rather
   * than convenient: `open` loads and validates every live index and refuses
   * to start when one fails, so a store that is up has had every live file
   * verified already. The question a monitor is left asking is "did we
   * quarantine something and lose vectors?", which is exactly what this
   * answers without reading a payload byte.
   *
   * It cannot tell you why a database refuses to OPEN. Use
   * `SparrowDB.vectorIndexLoadFailures` for that.
   *
   * Not to be confused with the instance method `db.vectorIndexHealth(label,
   * prop)`, which counts reachable vectors inside one healthy index.
   *
   * ```typescript
   * const report = SparrowDB.vectorIndexDamageScan('/path/to/my.db')
   * if (report.unscannable) page('cannot read the index directory')
   * else if (!report.healthy) page(report.active.map(f => `${f.label}.${f.prop}`))
   * ```
   */
  static vectorIndexDamageScan(path: string): VectorIndexDamageReport
  /**
   * Execute a Cypher query and return `{ columns, rows }`.
   *
   * Each row is a plain object mapping column name → value.
   * Supported value types: `null`, `number`, `boolean`, `string`,
   * `{ $type: "node", id: string }`, `{ $type: "edge", id: string }`.
   * Note: `Int64` values outside `±(2^53-1)` are also returned as strings.
   */
  execute(cypher: string): QueryResult
  /**
   * Execute a Cypher query with named parameters and return `{ columns, rows }`.
   *
   * `params` is a plain JS object whose keys correspond to `$name` references
   * in the Cypher source.  Values may be:
   *
   * - `null` → `Value::Null`
   * - `boolean`
   * - `number` (integer → `Int64`, otherwise `Float64`)
   * - `string`
   * - `Array<number>` — the canonical shape for vector embeddings; the engine
   *   accepts these for `SET n.embedding = $emb` and similar mutations on
   *   HNSW-indexed properties.
   * - `Array<any>` — generic list parameters (e.g. `UNWIND $names AS name`)
   * - `object` — converted to a property map; rarely needed
   *
   * This unblocks the dedup-gate write pattern from KMSmcp issue #67:
   * the Cypher parser cannot accept 768-element list literals, so 768d
   * embeddings must be passed as parameters.  The engine surface
   * (`GraphDb::execute_with_params`) has supported this since SPA-218; this
   * binding simply exposes it to JS callers.
   *
   * **HNSW note (as of 0.1.23):** When the target property has a vector index,
   * `SET n.prop = $vec` now ALSO writes the vector into the HNSW index.
   * Previously the property was stored but the HNSW file was not updated —
   * a silent data-loss bug surfaced by KMSmcp channel message #202.
   *
   * **`CREATE` support (SPA-480):** standalone `CREATE (:Label {prop: $p})`
   * and `MATCH ... CREATE` (including edge properties, e.g.
   * `CREATE (a)-[:R {weight: $w}]->(b)`) now accept `$param` values. This
   * closes the last gap in the parameterized-query story: building a
   * `CREATE` from untrusted input via `executeWithParams` no longer
   * requires string interpolation, so a value like `'", role: "admin'` is
   * stored as a literal property value instead of being able to inject
   * Cypher syntax. Previously these statements threw
   * `"parameterized MATCH...CREATE and standalone CREATE are not yet
   * supported"`.
   *
   * ```typescript
   * const emb = Array.from(new Float32Array(768))  // your model output
   * db.executeWithParams(
   *   "MERGE (k:Memory {id: $id}) SET k.embedding = $emb",
   *   { id: 'abc-123', emb }
   * )
   * ```
   *
   * Throws `TypeError` if `params` is not an object or contains a value
   * that cannot be converted to a SparrowDB engine value.
   * Throws on Cypher parse / bind / execution errors (passed through from
   * the engine).
   */
  executeWithParams(cypher: string, params: any): QueryResult
  /** Flush the WAL and compact the database. */
  checkpoint(): void
  /** Checkpoint + sort neighbour lists for faster traversal. */
  optimize(): void
  /**
   * Open a read-only snapshot transaction pinned to the current committed
   * state.  Multiple readers may coexist with an active writer.
   */
  beginRead(): ReadTx
  /**
   * Open a write transaction.  Only one writer may be active at a time;
   * throws `WriterBusy` if another writer is already open.
   */
  beginWrite(): WriteTx
  /**
   * Create an HNSW vector similarity index on `(label, property)`.
   *
   * `dimensions` — number of f32 components in each embedding vector.
   * `similarity` — distance metric: `"cosine"` (default), `"euclidean"`, or `"dot"`.
   *
   * Idempotent: if an index already exists for this `(label, property)` pair,
   * this is a no-op.
   *
   * ```typescript
   * db.createVectorIndex('Memory', 'embedding', 768)
   * db.createVectorIndex('Memory', 'embedding', 768, 'cosine')
   * ```
   */
  createVectorIndex(label: string, property: string, dimensions: number, similarity?: string | undefined | null): void
  /**
   * Directly insert a vector into the HNSW index for an existing node.
   *
   * This is the explicit backfill API requested by KMSmcp (ch #202).  It is
   * useful when nodes were created without an inline embedding and you want to
   * populate the HNSW index without DETACH DELETE + recreate.
   *
   * - `label`    — node label (e.g. `"Memory"`)
   * - `property` — the vector property name (e.g. `"embedding"`)
   * - `node_id`  — the **user-facing** `id` property value (string), not the
   *                internal u64 slot number.
   * - `vector`   — Float32Array of `dimensions` elements.
   *
   * Throws `RangeError` if no vector index exists for `(label, property)`.
   * Throws `TypeError`  if `vector.length` does not match the index dimensions.
   * Throws `RangeError` if no node with `id = node_id` is found under `label`.
   *
   * ```typescript
   * db.addToVectorIndex('Memory', 'embedding', 'node-uuid-here', myFloat32Array)
   * ```
   */
  addToVectorIndex(label: string, property: string, nodeId: string, vector: Float32Array): void
  /**
   * Whether `node_id` currently has a vector in the `(label, property)`
   * index.
   *
   * This answers the question `vectorSearch` cannot.  "Not returned by
   * `vectorSearch`" and "absent from the index" are different facts, and
   * with only `vectorSearch` to probe with there was no way to tell them
   * apart — which is how issue #443 stayed invisible, and how an
   * investigation twice concluded that writes were failing when the vectors
   * were in fact stored and merely unreachable.
   *
   * Returns `false` when the node has no vector, and also when no node with
   * that id exists.  Throws `RangeError` only if the index itself is absent.
   *
   * ```typescript
   * db.hasVector('Memory', 'embedding', 'node-uuid-here')  // => true
   * ```
   */
  hasVector(label: string, property: string, nodeId: string): boolean
  /**
   * Coverage of the `(label, property)` index: how many vectors are stored
   * versus how many `vectorSearch` can actually reach.
   *
   * `stored === reachable` on a healthy index.  Any gap is silent recall
   * loss: those vectors are in the file, `hasVector` reports them present,
   * and no search will ever return them.  Issue #443 went unnoticed for
   * months because this number was not observable — the live store sat at
   * 1347 stored / 1307 reachable with nothing to surface it.
   *
   * Cheap: one graph walk, no distance arithmetic.
   *
   * ```typescript
   * const h = db.vectorIndexHealth('Memory', 'embedding')
   * // { stored: 1347, reachable: 1307, unreachable: 40 }
   * ```
   */
  vectorIndexHealth(label: string, property: string): VectorIndexHealth
  /**
   * Reconnect every stored-but-unreachable vector and persist the result.
   * Returns the number of vectors re-linked.
   *
   * Needed for any index written before the reciprocal-link guarantee
   * shipped: those orphans live in the file, and nothing else repairs them —
   * re-inserting the same node takes the "already present" path, so a
   * backfill cannot heal it either.
   *
   * A no-op (returns 0) on a healthy index, so it is safe to call on
   * startup.
   *
   * ```typescript
   * const n = db.repairVectorIndex('Memory', 'embedding')  // => 40
   * ```
   */
  repairVectorIndex(label: string, property: string): number
  /**
   * Search the HNSW vector index for `k` nearest neighbours.
   *
   * Returns results sorted by descending similarity score (highest first).
   *
   * `query_vector` — Float32Array of `dimensions` elements.
   * `k`            — maximum number of results to return.
   * `ef`           — optional search expansion factor (higher = more accurate,
   *                  slower; defaults to `max(k * 4, 50)`).
   *
   * Throws `RangeError` if no index exists for `(label, property)`.
   * Throws `TypeError`  if `query_vector.length` does not match the index
   *                     dimensionality.
   *
   * ```typescript
   * const results = db.vectorSearch('Memory', 'embedding', queryVec, 10)
   * // results: Array<{ id: string, score: number }>
   * ```
   */
  vectorSearch(label: string, property: string, queryVector: Float32Array, k: number, ef?: number | undefined | null): Array<NodeResult>
  /**
   * Compute the similarity between two vectors.
   *
   * `metric` — `"cosine"` (default), `"euclidean"`, or `"dot"`.
   *
   * Both arrays must have the same length.  Throws `TypeError` on mismatch.
   *
   * ```typescript
   * const sim = db.vectorSimilarity(a, b)          // cosine
   * const dist = db.vectorSimilarity(a, b, 'euclidean')
   * ```
   */
  vectorSimilarity(a: Float32Array, b: Float32Array, metric?: string | undefined | null): number
  /**
   * Create a BM25 full-text index on `(label, property)`.
   *
   * Once created, nodes inserted with `CREATE (n:Label {property: "text…"})`
   * are automatically indexed.  The optional `name` argument is ignored for
   * now (reserved for named-index DDL compatibility).
   *
   * Idempotent: a second call for the same `(label, property)` is a no-op.
   *
   * ```typescript
   * db.createFulltextIndex('Memory', 'content')
   * ```
   */
  createFulltextIndex(label: string, property: string, name?: string | undefined | null): void
  /**
   * Search the BM25 full-text index for `(label, property)`.
   *
   * Returns up to `limit` results (default 10) sorted by descending BM25 score.
   *
   * ```typescript
   * const hits = db.fulltextSearch('Memory', 'content', 'neural networks', 5)
   * // hits: Array<{ id: string, score: number }>
   * ```
   */
  fulltextSearch(label: string, property: string, query: string, limit?: number | undefined | null): Array<NodeResult>
  /**
   * Hybrid vector + full-text search using Reciprocal Rank Fusion (RRF).
   *
   * Runs HNSW vector search and BM25 full-text search independently, then
   * fuses the ranked lists.  Missing indexes are treated as empty — so if
   * only a vector index exists the call degrades gracefully to vector-only.
   *
   * `label`           — node label (e.g. `"Memory"`)
   * `text_property`   — property holding the text content (for BM25)
   * `vector_property` — property holding the embedding (for HNSW)
   * `query_vector`    — Float32Array query embedding
   * `text_query`      — query string for full-text search
   * `k`               — max results to return (default 10)
   * `alpha`           — optional; when supplied uses weighted fusion:
   *                     `alpha * norm_vec + (1-alpha) * norm_bm25`.
   *                     When omitted, uses RRF with k=60.
   *
   * ```typescript
   * const hits = db.hybridSearch('Memory', 'content', 'embedding', queryVec, 'neural networks', 10)
   * // hits: Array<{ id: string, score: number }>
   *
   * // Weighted fusion (vector-heavy):
   * const hits2 = db.hybridSearch('Memory', 'content', 'embedding', queryVec, 'query', 10, 0.7)
   * ```
   */
  hybridSearch(label: string, textProperty: string, vectorProperty: string, queryVector: Float32Array, textQuery: string, k?: number | undefined | null, alpha?: number | undefined | null): Array<NodeResult>
}
/**
 * Read-only snapshot transaction.  Sees only data committed at or before the
 * snapshot point; immune to concurrent writes.
 */
export declare class ReadTx {
  /**
   * The committed `txn_id` this reader is pinned to.
   *
   * Returned as a decimal **string** to preserve the full u64 range —
   * JavaScript's `Number` can only represent integers up to 2^53-1 safely.
   */
  get snapshotTxnId(): string
  /**
   * Execute a read-only Cypher query against this snapshot.
   *
   * **Not yet implemented.** The underlying `GraphDb::execute` always reads
   * from the latest committed state; snapshot-pinned execution is tracked
   * in SPA-100.  Use `SparrowDB.execute()` for reads against current state.
   *
   * Throws always until SPA-100 lands.
   */
  execute(cypher: string): QueryResult
}
/**
 * Write transaction.  Commit explicitly; dropping without committing rolls
 * back all staged changes.
 */
export declare class WriteTx {
  /**
   * Execute a Cypher mutation statement inside this transaction.
   *
   * Returns `{ columns, rows }` (typically empty for write statements).
   */
  execute(cypher: string): QueryResult
  /**
   * Commit all staged changes and return the new transaction id.
   *
   * The id is returned as a decimal **string** to preserve the full u64
   * range — JavaScript's `Number` can only represent integers up to 2^53-1.
   *
   * Throws if the transaction was already committed or rolled back, or if
   * a write-write conflict is detected.
   */
  commit(): string
  /**
   * Roll back all staged changes explicitly.  Equivalent to dropping the
   * transaction without committing.
   */
  rollback(): void
}
