/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * A single result row from a vector or full-text search.
 *
 * ```typescript
 * interface NodeResult {
 *   /** Node ID as a decimal string (full u64 range, JS-safe). */
 *   id: string;
 *   /** Relevance score: cosine similarity / BM25 score / distance. */
 *   score: number;
 * }
 * ```
 */
export interface NodeResult {
  /** Node ID as a decimal string to preserve u64 precision across the JS boundary. */
  id: string
  /** Relevance score widened to f64 for JS compatibility. */
  score: number
}
/**
 * Top-level database handle.
 *
 * ```typescript
 * import { SparrowDB } from 'sparrowdb'
 *
 * const db = SparrowDB.open('/path/to/my.db')
 * const result = db.execute('MATCH (n:Person) RETURN n.name LIMIT 5')
 * for (const row of result.rows) {
 *   console.log(row['n.name'])
 * }
 * db.checkpoint()
 * ```
 */
export declare class SparrowDB {
  /**
   * Open (or create) a SparrowDB database at `path`.
   *
   * Throws if the path cannot be created or the database files are corrupt.
   */
  static open(path: string): SparrowDb
  /**
   * Execute a Cypher query and return `{ columns, rows }`.
   *
   * Each row is a plain object mapping column name → value.
   * Supported value types: `null`, `number`, `boolean`, `string`,
   * `{ $type: "node", id: string }`, `{ $type: "edge", id: string }`.
   * Note: `Int64` values outside `±(2^53-1)` are also returned as strings.
   */
  execute(cypher: string): any
  /** Flush the WAL and compact the database. */
  checkpoint(): void
  /** Checkpoint + sort neighbour lists for faster traversal. */
  optimize(): void
  /**
   * Open a read-only snapshot transaction pinned to the current committed
   * state.  Multiple readers may coexist with an active writer.
   */
  beginRead(): ReadTx
  /**
   * Open a write transaction.  Only one writer may be active at a time;
   * throws `WriterBusy` if another writer is already open.
   */
  beginWrite(): WriteTx
  /**
   * Create an HNSW vector similarity index on `(label, property)`.
   *
   * `dimensions` — number of f32 components in each embedding vector.
   * `similarity` — distance metric: `"cosine"` (default), `"euclidean"`, or `"dot"`.
   *
   * Idempotent: if an index already exists for this `(label, property)` pair,
   * this is a no-op.
   *
   * ```typescript
   * db.createVectorIndex('Memory', 'embedding', 768)
   * db.createVectorIndex('Memory', 'embedding', 768, 'cosine')
   * ```
   */
  createVectorIndex(label: string, property: string, dimensions: number, similarity?: string | undefined | null): void
  /**
   * Search the HNSW vector index for `k` nearest neighbours.
   *
   * Returns results sorted by descending similarity score (highest first).
   *
   * `query_vector` — Float32Array of `dimensions` elements.
   * `k`            — maximum number of results to return.
   * `ef`           — optional search expansion factor (higher = more accurate,
   *                  slower; defaults to `max(k * 4, 50)`).
   *
   * Throws `RangeError` if no index exists for `(label, property)`.
   * Throws `TypeError`  if `query_vector.length` does not match the index
   *                     dimensionality.
   *
   * ```typescript
   * const results = db.vectorSearch('Memory', 'embedding', queryVec, 10)
   * // results: Array<{ id: string, score: number }>
   * ```
   */
  vectorSearch(label: string, property: string, queryVector: Float32Array, k: number, ef?: number | undefined | null): Array<NodeResult>
  /**
   * Compute the similarity between two vectors.
   *
   * `metric` — `"cosine"` (default), `"euclidean"`, or `"dot"`.
   *
   * Both arrays must have the same length.  Throws `TypeError` on mismatch.
   *
   * ```typescript
   * const sim = db.vectorSimilarity(a, b)          // cosine
   * const dist = db.vectorSimilarity(a, b, 'euclidean')
   * ```
   */
  vectorSimilarity(a: Float32Array, b: Float32Array, metric?: string | undefined | null): number
  /**
   * Create a BM25 full-text index on `(label, property)`.
   *
   * Once created, nodes inserted with `CREATE (n:Label {property: "text…"})`
   * are automatically indexed.  The optional `name` argument is ignored for
   * now (reserved for named-index DDL compatibility).
   *
   * Idempotent: a second call for the same `(label, property)` is a no-op.
   *
   * ```typescript
   * db.createFulltextIndex('Memory', 'content')
   * ```
   */
  createFulltextIndex(label: string, property: string, name?: string | undefined | null): void
  /**
   * Search the BM25 full-text index for `(label, property)`.
   *
   * Returns up to `limit` results (default 10) sorted by descending BM25 score.
   *
   * ```typescript
   * const hits = db.fulltextSearch('Memory', 'content', 'neural networks', 5)
   * // hits: Array<{ id: string, score: number }>
   * ```
   */
  fulltextSearch(label: string, property: string, query: string, limit?: number | undefined | null): Array<NodeResult>
  /**
   * Hybrid vector + full-text search using Reciprocal Rank Fusion (RRF).
   *
   * Runs HNSW vector search and BM25 full-text search independently, then
   * fuses the ranked lists.  Missing indexes are treated as empty — so if
   * only a vector index exists the call degrades gracefully to vector-only.
   *
   * `label`           — node label (e.g. `"Memory"`)
   * `text_property`   — property holding the text content (for BM25)
   * `vector_property` — property holding the embedding (for HNSW)
   * `query_vector`    — Float32Array query embedding
   * `text_query`      — query string for full-text search
   * `k`               — max results to return (default 10)
   * `alpha`           — optional; when supplied uses weighted fusion:
   *                     `alpha * norm_vec + (1-alpha) * norm_bm25`.
   *                     When omitted, uses RRF with k=60.
   *
   * ```typescript
   * const hits = db.hybridSearch('Memory', 'content', 'embedding', queryVec, 'neural networks', 10)
   * // hits: Array<{ id: string, score: number }>
   *
   * // Weighted fusion (vector-heavy):
   * const hits2 = db.hybridSearch('Memory', 'content', 'embedding', queryVec, 'query', 10, 0.7)
   * ```
   */
  hybridSearch(label: string, textProperty: string, vectorProperty: string, queryVector: Float32Array, textQuery: string, k?: number | undefined | null, alpha?: number | undefined | null): Array<NodeResult>
}
/**
 * Read-only snapshot transaction.  Sees only data committed at or before the
 * snapshot point; immune to concurrent writes.
 */
export declare class ReadTx {
  /**
   * The committed `txn_id` this reader is pinned to.
   *
   * Returned as a decimal **string** to preserve the full u64 range —
   * JavaScript's `Number` can only represent integers up to 2^53-1 safely.
   */
  get snapshotTxnId(): string
  /**
   * Execute a read-only Cypher query against this snapshot.
   *
   * **Not yet implemented.** The underlying `GraphDb::execute` always reads
   * from the latest committed state; snapshot-pinned execution is tracked
   * in SPA-100.  Use `SparrowDB.execute()` for reads against current state.
   *
   * Throws always until SPA-100 lands.
   */
  execute(cypher: string): any
}
/**
 * Write transaction.  Commit explicitly; dropping without committing rolls
 * back all staged changes.
 */
export declare class WriteTx {
  /**
   * Execute a Cypher mutation statement inside this transaction.
   *
   * Returns `{ columns, rows }` (typically empty for write statements).
   */
  execute(cypher: string): any
  /**
   * Commit all staged changes and return the new transaction id.
   *
   * The id is returned as a decimal **string** to preserve the full u64
   * range — JavaScript's `Number` can only represent integers up to 2^53-1.
   *
   * Throws if the transaction was already committed or rolled back, or if
   * a write-write conflict is detected.
   */
  commit(): string
  /**
   * Roll back all staged changes explicitly.  Equivalent to dropping the
   * transaction without committing.
   */
  rollback(): void
}
