/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The result of a Cypher query: a list of column names and a list of rows.
 *
 * Each row is an object mapping column name to its value.  Value types: `null`,
 * `number`, `boolean`, `string`, `{ $type: "node", id: string }`,
 * `{ $type: "edge", id: string }`.
 *
 * ```typescript
 * interface QueryResult {
 *   columns: string[];
 *   rows: Record<string, unknown>[];
 * }
 * ```
 */
export interface QueryResult {
  /** Ordered list of column names returned by the query. */
  columns: Array<string>
  /** One element per result row; each row maps column name to its value. */
  rows: Array<any>
}
/**
 * A single result row from a vector or full-text search.
 *
 * ```typescript
 * interface NodeResult {
 *   /** Node ID as a decimal string (full u64 range, JS-safe). */
 *   id: string;
 *   /** Relevance score: cosine similarity / BM25 score / distance. */
 *   score: number;
 * }
 * ```
 */
export interface NodeResult {
  /** Node ID as a decimal string to preserve u64 precision across the JS boundary. */
  id: string
  /** Relevance score widened to f64 for JS compatibility. */
  score: number
}
/**
 * Coverage report for an HNSW index — see `SparrowDB.vectorIndexHealth`.
 *
 * ```typescript
 * interface VectorIndexHealth {
 *   stored: number;       // vectors stored in the index
 *   reachable: number;    // vectors `vectorSearch` can actually reach
 *   unreachable: number;  // stored - reachable; must be 0 when healthy
 * }
 * ```
 *
 * Note the `//` comments above rather than nested doc comments: a `*\/` inside
 * a generated JSDoc block closes it early, which is why the checked-in
 * `npm/sparrowdb/index.d.ts` does not currently parse as TypeScript.
 */
export interface VectorIndexHealth {
  /** Vectors stored in the index. */
  stored: number
  /** Vectors reachable by greedy traversal from the entry point. */
  reachable: number
  /** `stored - reachable`. Non-zero means silent recall loss. */
  unreachable: number
}
/**
 * Top-level database handle.
 *
 * ```typescript
 * import { SparrowDB } from 'sparrowdb'
 *
 * const db = SparrowDB.open('/path/to/my.db')
 * const result = db.execute('MATCH (n:Person) RETURN n.name LIMIT 5')
 * for (const row of result.rows) {
 *   console.log(row['n.name'])
 * }
 * db.checkpoint()
 * ```
 */
export declare class SparrowDB {
  /**
   * Open (or create) a SparrowDB database at `path`.
   *
   * Throws if the path cannot be created or the database files are corrupt.
   */
  static open(path: string): SparrowDB
  /**
   * Execute a Cypher query and return `{ columns, rows }`.
   *
   * Each row is a plain object mapping column name → value.
   * Supported value types: `null`, `number`, `boolean`, `string`,
   * `{ $type: "node", id: string }`, `{ $type: "edge", id: string }`.
   * Note: `Int64` values outside `±(2^53-1)` are also returned as strings.
   */
  execute(cypher: string): QueryResult
  /**
   * Execute a Cypher query with named parameters and return `{ columns, rows }`.
   *
   * `params` is a plain JS object whose keys correspond to `$name` references
   * in the Cypher source.  Values may be:
   *
   * - `null` → `Value::Null`
   * - `boolean`
   * - `number` (integer → `Int64`, otherwise `Float64`)
   * - `string`
   * - `Array<number>` — the canonical shape for vector embeddings; the engine
   *   accepts these for `SET n.embedding = $emb` and similar mutations on
   *   HNSW-indexed properties.
   * - `Array<any>` — generic list parameters (e.g. `UNWIND $names AS name`)
   * - `object` — converted to a property map; rarely needed
   *
   * This unblocks the dedup-gate write pattern from KMSmcp issue #67:
   * the Cypher parser cannot accept 768-element list literals, so 768d
   * embeddings must be passed as parameters.  The engine surface
   * (`GraphDb::execute_with_params`) has supported this since SPA-218; this
   * binding simply exposes it to JS callers.
   *
   * **HNSW note (as of 0.1.23):** When the target property has a vector index,
   * `SET n.prop = $vec` now ALSO writes the vector into the HNSW index.
   * Previously the property was stored but the HNSW file was not updated —
   * a silent data-loss bug surfaced by KMSmcp channel message #202.
   *
   * ```typescript
   * const emb = Array.from(new Float32Array(768))  // your model output
   * db.executeWithParams(
   *   "MERGE (k:Memory {id: $id}) SET k.embedding = $emb",
   *   { id: 'abc-123', emb }
   * )
   * ```
   *
   * Throws `TypeError` if `params` is not an object or contains a value
   * that cannot be converted to a SparrowDB engine value.
   * Throws on Cypher parse / bind / execution errors (passed through from
   * the engine).
   */
  executeWithParams(cypher: string, params: any): QueryResult
  /** Flush the WAL and compact the database. */
  checkpoint(): void
  /** Checkpoint + sort neighbour lists for faster traversal. */
  optimize(): void
  /**
   * Open a read-only snapshot transaction pinned to the current committed
   * state.  Multiple readers may coexist with an active writer.
   */
  beginRead(): ReadTx
  /**
   * Open a write transaction.  Only one writer may be active at a time;
   * throws `WriterBusy` if another writer is already open.
   */
  beginWrite(): WriteTx
  /**
   * Create an HNSW vector similarity index on `(label, property)`.
   *
   * `dimensions` — number of f32 components in each embedding vector.
   * `similarity` — distance metric: `"cosine"` (default), `"euclidean"`, or `"dot"`.
   *
   * Idempotent: if an index already exists for this `(label, property)` pair,
   * this is a no-op.
   *
   * ```typescript
   * db.createVectorIndex('Memory', 'embedding', 768)
   * db.createVectorIndex('Memory', 'embedding', 768, 'cosine')
   * ```
   */
  createVectorIndex(label: string, property: string, dimensions: number, similarity?: string | undefined | null): void
  /**
   * Directly insert a vector into the HNSW index for an existing node.
   *
   * This is the explicit backfill API requested by KMSmcp (ch #202).  It is
   * useful when nodes were created without an inline embedding and you want to
   * populate the HNSW index without DETACH DELETE + recreate.
   *
   * - `label`    — node label (e.g. `"Memory"`)
   * - `property` — the vector property name (e.g. `"embedding"`)
   * - `node_id`  — the **user-facing** `id` property value (string), not the
   *                internal u64 slot number.
   * - `vector`   — Float32Array of `dimensions` elements.
   *
   * Throws `RangeError` if no vector index exists for `(label, property)`.
   * Throws `TypeError`  if `vector.length` does not match the index dimensions.
   * Throws `RangeError` if no node with `id = node_id` is found under `label`.
   *
   * ```typescript
   * db.addToVectorIndex('Memory', 'embedding', 'node-uuid-here', myFloat32Array)
   * ```
   */
  addToVectorIndex(label: string, property: string, nodeId: string, vector: Float32Array): void
  /**
   * Whether `node_id` currently has a vector in the `(label, property)`
   * index.
   *
   * This answers the question `vectorSearch` cannot.  "Not returned by
   * `vectorSearch`" and "absent from the index" are different facts, and
   * with only `vectorSearch` to probe with there was no way to tell them
   * apart — which is how issue #443 stayed invisible, and how an
   * investigation twice concluded that writes were failing when the vectors
   * were in fact stored and merely unreachable.
   *
   * Returns `false` when the node has no vector, and also when no node with
   * that id exists.  Throws `RangeError` only if the index itself is absent.
   *
   * ```typescript
   * db.hasVector('Memory', 'embedding', 'node-uuid-here')  // => true
   * ```
   */
  hasVector(label: string, property: string, nodeId: string): boolean
  /**
   * Coverage of the `(label, property)` index: how many vectors are stored
   * versus how many `vectorSearch` can actually reach.
   *
   * `stored === reachable` on a healthy index.  Any gap is silent recall
   * loss: those vectors are in the file, `hasVector` reports them present,
   * and no search will ever return them.  Issue #443 went unnoticed for
   * months because this number was not observable — the live store sat at
   * 1347 stored / 1307 reachable with nothing to surface it.
   *
   * Cheap: one graph walk, no distance arithmetic.
   *
   * ```typescript
   * const h = db.vectorIndexHealth('Memory', 'embedding')
   * // { stored: 1347, reachable: 1307, unreachable: 40 }
   * ```
   */
  vectorIndexHealth(label: string, property: string): VectorIndexHealth
  /**
   * Reconnect every stored-but-unreachable vector and persist the result.
   * Returns the number of vectors re-linked.
   *
   * Needed for any index written before the reciprocal-link guarantee
   * shipped: those orphans live in the file, and nothing else repairs them —
   * re-inserting the same node takes the "already present" path, so a
   * backfill cannot heal it either.
   *
   * A no-op (returns 0) on a healthy index, so it is safe to call on
   * startup.
   *
   * ```typescript
   * const n = db.repairVectorIndex('Memory', 'embedding')  // => 40
   * ```
   */
  repairVectorIndex(label: string, property: string): number
  /**
   * Search the HNSW vector index for `k` nearest neighbours.
   *
   * Returns results sorted by descending similarity score (highest first).
   *
   * `query_vector` — Float32Array of `dimensions` elements.
   * `k`            — maximum number of results to return.
   * `ef`           — optional search expansion factor (higher = more accurate,
   *                  slower; defaults to `max(k * 4, 50)`).
   *
   * Throws `RangeError` if no index exists for `(label, property)`.
   * Throws `TypeError`  if `query_vector.length` does not match the index
   *                     dimensionality.
   *
   * ```typescript
   * const results = db.vectorSearch('Memory', 'embedding', queryVec, 10)
   * // results: Array<{ id: string, score: number }>
   * ```
   */
  vectorSearch(label: string, property: string, queryVector: Float32Array, k: number, ef?: number | undefined | null): Array<NodeResult>
  /**
   * Compute the similarity between two vectors.
   *
   * `metric` — `"cosine"` (default), `"euclidean"`, or `"dot"`.
   *
   * Both arrays must have the same length.  Throws `TypeError` on mismatch.
   *
   * ```typescript
   * const sim = db.vectorSimilarity(a, b)          // cosine
   * const dist = db.vectorSimilarity(a, b, 'euclidean')
   * ```
   */
  vectorSimilarity(a: Float32Array, b: Float32Array, metric?: string | undefined | null): number
  /**
   * Create a BM25 full-text index on `(label, property)`.
   *
   * Once created, nodes inserted with `CREATE (n:Label {property: "text…"})`
   * are automatically indexed.  The optional `name` argument is ignored for
   * now (reserved for named-index DDL compatibility).
   *
   * Idempotent: a second call for the same `(label, property)` is a no-op.
   *
   * ```typescript
   * db.createFulltextIndex('Memory', 'content')
   * ```
   */
  createFulltextIndex(label: string, property: string, name?: string | undefined | null): void
  /**
   * Search the BM25 full-text index for `(label, property)`.
   *
   * Returns up to `limit` results (default 10) sorted by descending BM25 score.
   *
   * ```typescript
   * const hits = db.fulltextSearch('Memory', 'content', 'neural networks', 5)
   * // hits: Array<{ id: string, score: number }>
   * ```
   */
  fulltextSearch(label: string, property: string, query: string, limit?: number | undefined | null): Array<NodeResult>
  /**
   * Hybrid vector + full-text search using Reciprocal Rank Fusion (RRF).
   *
   * Runs HNSW vector search and BM25 full-text search independently, then
   * fuses the ranked lists.  Missing indexes are treated as empty — so if
   * only a vector index exists the call degrades gracefully to vector-only.
   *
   * `label`           — node label (e.g. `"Memory"`)
   * `text_property`   — property holding the text content (for BM25)
   * `vector_property` — property holding the embedding (for HNSW)
   * `query_vector`    — Float32Array query embedding
   * `text_query`      — query string for full-text search
   * `k`               — max results to return (default 10)
   * `alpha`           — optional; when supplied uses weighted fusion:
   *                     `alpha * norm_vec + (1-alpha) * norm_bm25`.
   *                     When omitted, uses RRF with k=60.
   *
   * ```typescript
   * const hits = db.hybridSearch('Memory', 'content', 'embedding', queryVec, 'neural networks', 10)
   * // hits: Array<{ id: string, score: number }>
   *
   * // Weighted fusion (vector-heavy):
   * const hits2 = db.hybridSearch('Memory', 'content', 'embedding', queryVec, 'query', 10, 0.7)
   * ```
   */
  hybridSearch(label: string, textProperty: string, vectorProperty: string, queryVector: Float32Array, textQuery: string, k?: number | undefined | null, alpha?: number | undefined | null): Array<NodeResult>
}
/**
 * Read-only snapshot transaction.  Sees only data committed at or before the
 * snapshot point; immune to concurrent writes.
 */
export declare class ReadTx {
  /**
   * The committed `txn_id` this reader is pinned to.
   *
   * Returned as a decimal **string** to preserve the full u64 range —
   * JavaScript's `Number` can only represent integers up to 2^53-1 safely.
   */
  get snapshotTxnId(): string
  /**
   * Execute a read-only Cypher query against this snapshot.
   *
   * **Not yet implemented.** The underlying `GraphDb::execute` always reads
   * from the latest committed state; snapshot-pinned execution is tracked
   * in SPA-100.  Use `SparrowDB.execute()` for reads against current state.
   *
   * Throws always until SPA-100 lands.
   */
  execute(cypher: string): QueryResult
}
/**
 * Write transaction.  Commit explicitly; dropping without committing rolls
 * back all staged changes.
 */
export declare class WriteTx {
  /**
   * Execute a Cypher mutation statement inside this transaction.
   *
   * Returns `{ columns, rows }` (typically empty for write statements).
   */
  execute(cypher: string): QueryResult
  /**
   * Commit all staged changes and return the new transaction id.
   *
   * The id is returned as a decimal **string** to preserve the full u64
   * range — JavaScript's `Number` can only represent integers up to 2^53-1.
   *
   * Throws if the transaction was already committed or rolled back, or if
   * a write-write conflict is detected.
   */
  commit(): string
  /**
   * Roll back all staged changes explicitly.  Equivalent to dropping the
   * transaction without committing.
   */
  rollback(): void
}
