#!/usr/bin/env python3
"""Generate deterministic real-world fixture datasets for SparrowDB regression tests.

Produces two Cypher fixture files with node CREATE statements only.
Edge creation is handled in the Rust test code via WriteTx::create_edge,
since MATCH+CREATE edge patterns are not yet supported by the execution engine.

  fixtures/real_world/mini_social.cypher    — 1250 nodes (1000 Person, 50 Company, 200 Post)
  fixtures/real_world/mini_knowledge.cypher — 200 nodes (120 Fact, 80 Entity)

Run from the repository root:
  python3 scripts/generate_fixtures.py

The output is fully deterministic: same seed always produces the same files.
"""

import random
import os

# ── seed ────────────────────────────────────────────────────────────────────────
SEED = 42

# ── node counts ─────────────────────────────────────────────────────────────────
N_PERSONS = 1000
N_COMPANIES = 50
N_POSTS = 200
N_FACTS = 120
N_ENTITIES = 80


# ── helpers ─────────────────────────────────────────────────────────────────────

def esc(s: str) -> str:
    """Escape a string for use in a Cypher single-quoted literal."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def cypher_props(d: dict) -> str:
    """Render a dict as a Cypher property map literal."""
    parts = []
    for k, v in d.items():
        if isinstance(v, str):
            parts.append(f"{k}: '{esc(v)}'")
        elif isinstance(v, float):
            parts.append(f"{k}: {v:.4f}")
        else:
            parts.append(f"{k}: {v}")
    return "{" + ", ".join(parts) + "}"


# ── social graph vocabularies ────────────────────────────────────────────────────

FIRST_NAMES = [
    "Alice", "Bob", "Carol", "Dave", "Eve", "Frank", "Grace", "Hank", "Iris",
    "Jack", "Karen", "Liam", "Mia", "Noah", "Olivia", "Pete", "Quinn", "Rita",
    "Sam", "Tara", "Uma", "Vick", "Wren", "Xavi", "Yara", "Zoe",
]
LAST_NAMES = [
    "Smith", "Jones", "Chen", "Kim", "Patel", "Brown", "Davis", "Wilson",
    "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris",
    "Martin", "Garcia", "Martinez", "Robinson", "Clark",
]
CITIES = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia",
    "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville",
    "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco",
    "Seattle", "Denver", "Nashville",
]
INDUSTRIES = [
    "Technology", "Finance", "Healthcare", "Education", "Retail",
    "Manufacturing", "Media", "Consulting", "Legal", "Real Estate",
]
COMPANY_NAMES_LIST = [
    "Apex Solutions", "Blue Ridge Analytics", "Cascade Systems", "Delta Corp",
    "Echo Ventures", "Frontier Tech", "Gravity Labs", "Harbor Digital",
    "Ignite Networks", "Jade Innovations", "Kestrel Media", "Luminary Group",
    "Meridian Software", "Nexus AI", "Orbit Consulting", "Pinnacle Data",
    "Quantum Edge", "Radius Health", "Skyline Finance", "Titan Retail",
    "Umbrella Dynamics", "Vanguard Systems", "Wavelength Studios",
    "Xenith Labs", "Yellowstone Capital", "Zenith Solutions",
    "Arc Systems", "Beacon Analytics", "Cirrus Networks", "Dusk Robotics",
    "Ember Cloud", "Flux Capital", "Glide Tech", "Halo Security",
    "Indigo Media", "Junction AI", "Kinetic Labs", "Lattice Data",
    "Mosaic Finance", "Nova Health", "Onyx Consulting", "Pulse Retail",
    "Qubit Research", "Ridge Manufacturing", "Spark Legal", "Topaz Education",
    "Uplift Media", "Vertex Systems", "Warp Computing", "Axiom Ventures",
    "Bright Future Corp", "Crystal Dynamics",
]
POST_TEMPLATES = [
    "Excited to share my thoughts on {topic}!",
    "Just finished a great book about {topic}.",
    "Anyone else thinking about {topic} lately?",
    "Big news in the {topic} space today.",
    "Working on a project related to {topic} — loving it.",
    "Hot take: {topic} is underrated.",
    "Five things I learned about {topic} this week.",
    "The future of {topic} is looking bright.",
    "Why {topic} matters more than you think.",
    "Reflecting on {topic} and what it means for us.",
]
TOPICS = [
    "machine learning", "distributed systems", "graph databases", "open source",
    "remote work", "climate tech", "financial independence", "health tech",
    "developer experience", "data privacy", "AI safety", "web3",
    "edge computing", "quantum computing", "DevOps", "observability",
]


def generate_social_nodes(seed: int = SEED) -> list[str]:
    """Return Cypher CREATE statements for social graph nodes only."""
    rng = random.Random(seed)
    lines: list[str] = []

    lines.append("// mini_social.cypher — generated by scripts/generate_fixtures.py")
    lines.append(f"// seed={seed}")
    lines.append(f"// nodes: Person={N_PERSONS} Company={N_COMPANIES} Post={N_POSTS}")
    lines.append("// edges are created by the Rust test code (see regression_real_world.rs)")
    lines.append("")

    # ── Person nodes ────────────────────────────────────────────────────────────
    lines.append("// ── Person nodes ─────────────────────────────────────────────")
    for i in range(N_PERSONS):
        name = (
            rng.choice(FIRST_NAMES)
            + " "
            + rng.choice(LAST_NAMES)
            + f"_{i}"
        )
        age = rng.randint(18, 72)
        city = rng.choice(CITIES)
        email = f"user{i}@example.com"
        props = cypher_props({"name": name, "age": age, "city": city, "email": email})
        lines.append(f"CREATE (n:Person {props});")

    lines.append("")

    # ── Company nodes ───────────────────────────────────────────────────────────
    lines.append("// ── Company nodes ────────────────────────────────────────────")
    for j in range(N_COMPANIES):
        name = COMPANY_NAMES_LIST[j % len(COMPANY_NAMES_LIST)] + f" {j}"
        industry = rng.choice(INDUSTRIES)
        founded = rng.randint(1970, 2023)
        props = cypher_props({"name": name, "industry": industry, "founded": founded})
        lines.append(f"CREATE (n:Company {props});")

    lines.append("")

    # ── Post nodes ──────────────────────────────────────────────────────────────
    lines.append("// ── Post nodes ───────────────────────────────────────────────")
    for k in range(N_POSTS):
        topic = rng.choice(TOPICS)
        template = rng.choice(POST_TEMPLATES)
        content = template.format(topic=topic)
        year = rng.randint(2020, 2024)
        month = rng.randint(1, 12)
        day = rng.randint(1, 28)
        created_at = f"{year}-{month:02d}-{day:02d}"
        likes = rng.randint(0, 5000)
        props = cypher_props({"content": content, "created_at": created_at, "likes": likes})
        lines.append(f"CREATE (n:Post {props});")

    return lines


# ── knowledge graph vocabularies ─────────────────────────────────────────────────

FACT_TEMPLATES = [
    "{entity} is a type of {concept}.",
    "{entity} was founded in {year}.",
    "{entity} operates in the {domain} domain.",
    "Research shows {entity} improves {metric} by {pct} percent.",
    "{entity} depends on {concept} for core functionality.",
    "Studies indicate {entity} reduces {metric} by {pct} percent.",
    "{entity} is related to {concept} through {relation}.",
    "The {concept} paradigm underpins {entity}.",
    "{entity} integrates with {concept} systems.",
    "{entity} emerged from research on {concept}.",
]
ENTITIES_KG = [
    "GraphDB", "NeuralNet", "BlockChain", "CloudFunction", "DataPipeline",
    "KnowledgeGraph", "ReinforcementLearning", "ContainerOrchestration",
    "SemanticSearch", "DistributedLedger", "EdgeComputing", "FederatedLearning",
    "ZeroTrustSecurity", "EventSourcing", "CQRSPattern", "ServiceMesh",
    "DataLakehouse", "VectorDatabase", "LargeLanguageModel", "QuantumCircuit",
]
CONCEPTS = [
    "machine learning", "distributed systems", "cryptography", "data modeling",
    "graph theory", "information retrieval", "consensus algorithms",
    "natural language processing", "computer vision", "formal verification",
]
SOURCES = [
    "arxiv:2301.00001", "doi:10.1145/3318464", "wikipedia:en", "blog:acm.org",
    "paper:vldb2023", "report:gartner2024", "book:oreilly2022", "rfc:9110",
]
ENTITY_TYPES = [
    "Technology", "Algorithm", "Framework", "Protocol", "Concept",
    "Organization", "Person", "System", "Dataset", "Standard",
]


def generate_knowledge_nodes(seed: int = SEED) -> list[str]:
    """Return Cypher CREATE statements for knowledge graph nodes only."""
    rng = random.Random(seed + 1000)  # different substream from social graph
    lines: list[str] = []

    lines.append("// mini_knowledge.cypher — generated by scripts/generate_fixtures.py")
    lines.append(f"// seed={seed}")
    lines.append(f"// nodes: Fact={N_FACTS} Entity={N_ENTITIES}")
    lines.append("// edges are created by the Rust test code (see regression_real_world.rs)")
    lines.append("")

    # ── Fact nodes ──────────────────────────────────────────────────────────────
    lines.append("// ── Fact nodes ───────────────────────────────────────────────")
    for i in range(N_FACTS):
        entity = rng.choice(ENTITIES_KG)
        concept = rng.choice(CONCEPTS)
        template = rng.choice(FACT_TEMPLATES)
        content = template.format(
            entity=entity,
            concept=concept,
            year=rng.randint(1990, 2024),
            domain=rng.choice(CONCEPTS),
            metric=rng.choice(["latency", "throughput", "accuracy", "recall"]),
            pct=rng.randint(5, 80),
            relation=rng.choice(["inheritance", "composition", "delegation", "dependency"]),
        )
        source = rng.choice(SOURCES)
        confidence = round(rng.uniform(0.5, 1.0), 4)
        props = cypher_props({"content": content, "source": source, "confidence": confidence})
        lines.append(f"CREATE (n:Fact {props});")

    lines.append("")

    # ── Entity nodes ─────────────────────────────────────────────────────────────
    lines.append("// ── Entity nodes ─────────────────────────────────────────────")
    for j in range(N_ENTITIES):
        name = rng.choice(ENTITIES_KG) + f"_{j}"
        etype = rng.choice(ENTITY_TYPES)
        props = cypher_props({"name": name, "type": etype})
        lines.append(f"CREATE (n:Entity {props});")

    return lines


# ── main ─────────────────────────────────────────────────────────────────────────

def write_fixture(path: str, lines: list[str]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")
    node_lines = sum(1 for l in lines if l.startswith("CREATE"))
    print(f"wrote {path} ({node_lines} CREATE statements)")


def main() -> None:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    fixtures_dir = os.path.join(repo_root, "fixtures", "real_world")

    social_path = os.path.join(fixtures_dir, "mini_social.cypher")
    knowledge_path = os.path.join(fixtures_dir, "mini_knowledge.cypher")

    print(f"generating social graph nodes (seed={SEED}) ...")
    social_lines = generate_social_nodes(seed=SEED)
    write_fixture(social_path, social_lines)

    print(f"generating knowledge graph nodes (seed={SEED}) ...")
    knowledge_lines = generate_knowledge_nodes(seed=SEED)
    write_fixture(knowledge_path, knowledge_lines)

    print("done.")


if __name__ == "__main__":
    main()
