//! CI coverage for the Cypher template strings generated by the `sparrowdb-mcp`
//! tool handlers (closes #378).
//!
//! The MCP tools build Cypher via `format!()` macros in
//! `crates/sparrowdb-mcp/src/main.rs`.  When the parser changes, those
//! templates can break silently at runtime.  These tests run the *exact*
//! Cypher patterns each tool would emit against a real `GraphDb` so that any
//! parser regression is caught in CI immediately.
//!
//! Tools covered:
//! - `add_property`   — MATCH count query + MATCH … SET
//! - `create_entity`  — CREATE (no props) and CREATE (with props)
//! - `merge_node_by_property` — pre-merge MATCH count, MATCH-only path,
//!                              MATCH+SET path, and CREATE path

use sparrowdb::open;

// ── helpers ───────────────────────────────────────────────────────────────────

fn make_db() -> (tempfile::TempDir, sparrowdb::GraphDb) {
    let dir = tempfile::tempdir().expect("tempdir");
    let db = open(dir.path()).expect("open");
    (dir, db)
}

// ── add_property templates ────────────────────────────────────────────────────

/// The count-query template that `add_property` emits before the SET:
///
/// ```cypher
/// MATCH (n:{label} {{match_prop: '{match_val_escaped}'}}) RETURN count(n) AS cnt
/// ```
#[test]
fn mcp_template_add_property_count_query_parses_and_executes() {
    let (_dir, db) = make_db();

    // Seed a node so the count is non-zero.
    db.execute("CREATE (:Person {id: 'alice'})")
        .expect("seed CREATE must succeed");

    // Replicate what add_property emits for the count query.
    let label = "Person";
    let match_prop = "id";
    let match_val_escaped = "alice"; // escape_cypher_string("alice") = "alice"
    let count_query = format!(
        "MATCH (n:{label} {{{match_prop}: '{match_val_escaped}'}}) RETURN count(n) AS cnt",
    );

    let result = db
        .execute(&count_query)
        .expect("add_property count-query template must parse and execute without error");

    assert!(
        !result.rows.is_empty(),
        "count query must return at least one row; got: {:?}",
        result.rows
    );
}

/// The SET-query template that `add_property` emits when `matched > 0`:
///
/// ```cypher
/// MATCH (n:{label} {{match_prop: '{match_val_escaped}'}}) SET n.{set_prop} = {cypher_set_val}
/// ```
#[test]
fn mcp_template_add_property_set_query_parses_and_executes() {
    let (_dir, db) = make_db();

    db.execute("CREATE (:Person {id: 'bob'})")
        .expect("seed CREATE must succeed");

    // String set_val — json_scalar_to_cypher produces "'email@example.com'"
    let label = "Person";
    let match_prop = "id";
    let match_val_escaped = "bob";
    let set_prop = "email";
    let cypher_set_val = "'bob@example.com'";

    let set_query = format!(
        "MATCH (n:{label} {{{match_prop}: '{match_val_escaped}'}}) SET n.{set_prop} = {cypher_set_val}",
    );

    db.execute(&set_query)
        .expect("add_property SET-query template must parse and execute without error");

    // Verify the property was actually written.
    let verify = db
        .execute("MATCH (n:Person {id: 'bob'}) RETURN n.email")
        .expect("verify MATCH must succeed");
    assert_eq!(
        verify.rows.len(),
        1,
        "SET must have updated exactly one node; got: {:?}",
        verify.rows
    );
    let cell = verify.rows[0][0].to_string();
    assert!(
        cell.contains("bob@example.com"),
        "email property must be readable after SET; got: {cell}"
    );
}

/// SET with a numeric value — `json_scalar_to_cypher(42)` → `"42"`.
#[test]
fn mcp_template_add_property_set_numeric_value_parses_and_executes() {
    let (_dir, db) = make_db();

    db.execute("CREATE (:Item {sku: 'X1'})")
        .expect("seed CREATE must succeed");

    let set_query = "MATCH (n:Item {sku: 'X1'}) SET n.stock = 42";

    db.execute(set_query)
        .expect("add_property SET with numeric value must parse and execute");
}

/// SET with a boolean value — `json_scalar_to_cypher(true)` → `"true"`.
#[test]
fn mcp_template_add_property_set_boolean_value_parses_and_executes() {
    let (_dir, db) = make_db();

    db.execute("CREATE (:Feature {name: 'dark_mode'})")
        .expect("seed CREATE must succeed");

    let set_query = "MATCH (n:Feature {name: 'dark_mode'}) SET n.enabled = true";

    db.execute(set_query)
        .expect("add_property SET with boolean value must parse and execute");
}

// ── create_entity templates ───────────────────────────────────────────────────

/// CREATE with no properties — `props_clause` is empty:
///
/// ```cypher
/// CREATE (n:ClassName)
/// ```
#[test]
fn mcp_template_create_entity_no_props_parses_and_executes() {
    let (_dir, db) = make_db();

    // Mirrors: format!("CREATE (n:{}{})", class_name, props_clause) with props_clause = ""
    let class_name = "Company";
    let props_clause = "";
    let query = format!("CREATE (n:{class_name}{props_clause})");

    db.execute(&query)
        .expect("create_entity with no properties must parse and execute");

    let verify = db
        .execute("MATCH (n:Company) RETURN n")
        .expect("verify MATCH must succeed");
    assert_eq!(
        verify.rows.len(),
        1,
        "exactly one Company node must exist; got: {:?}",
        verify.rows
    );
}

/// CREATE with a single string property:
///
/// ```cypher
/// CREATE (n:Person {name: 'Alice'})
/// ```
#[test]
fn mcp_template_create_entity_with_string_prop_parses_and_executes() {
    let (_dir, db) = make_db();

    // Mirrors: format!("CREATE (n:{}{})", class_name, " {name: 'Alice'}")
    let class_name = "Person";
    let props_clause = " {name: 'Alice'}";
    let query = format!("CREATE (n:{class_name}{props_clause})");

    db.execute(&query)
        .expect("create_entity with string prop must parse and execute");

    let verify = db
        .execute("MATCH (n:Person {name: 'Alice'}) RETURN n.name")
        .expect("verify MATCH must succeed");
    assert_eq!(
        verify.rows.len(),
        1,
        "Person Alice must be retrievable; got: {:?}",
        verify.rows
    );
}

/// CREATE with mixed scalar property types (string + integer + boolean):
///
/// ```cypher
/// CREATE (n:Product {name: 'Widget', price: 99, active: true})
/// ```
#[test]
fn mcp_template_create_entity_with_mixed_props_parses_and_executes() {
    let (_dir, db) = make_db();

    // prop_parts joined: "name: 'Widget', price: 99, active: true"
    let class_name = "Product";
    let props_clause = " {name: 'Widget', price: 99, active: true}";
    let query = format!("CREATE (n:{class_name}{props_clause})");

    db.execute(&query)
        .expect("create_entity with mixed props must parse and execute");
}

// ── merge_node_by_property templates ─────────────────────────────────────────

/// Pre-merge count query (string match_value):
///
/// ```cypher
/// MATCH (n:{label} {{match_key: 'value'}}) RETURN count(n)
/// ```
#[test]
fn mcp_template_merge_node_count_query_string_parses_and_executes() {
    let (_dir, db) = make_db();

    db.execute("CREATE (:User {email: 'carol@example.com'})")
        .expect("seed CREATE must succeed");

    // json_scalar_to_cypher("carol@example.com") → "'carol@example.com'"
    let label = "User";
    let match_key = "email";
    let cypher_match_val = "'carol@example.com'";
    let count_query =
        format!("MATCH (n:{label} {{{match_key}: {cypher_match_val}}}) RETURN count(n)");

    let result = db
        .execute(&count_query)
        .expect("merge_node_by_property count-query template must parse and execute");

    assert!(
        !result.rows.is_empty(),
        "count query must return a row; got: {:?}",
        result.rows
    );
}

/// Pre-merge count query (integer match_value):
///
/// ```cypher
/// MATCH (n:Order {{order_id: 42}}) RETURN count(n)
/// ```
#[test]
fn mcp_template_merge_node_count_query_integer_parses_and_executes() {
    let (_dir, db) = make_db();

    db.execute("CREATE (:Order {order_id: 42})")
        .expect("seed CREATE must succeed");

    // json_scalar_to_cypher(42) → "42"
    let count_query = "MATCH (n:Order {order_id: 42}) RETURN count(n)";

    let result = db
        .execute(count_query)
        .expect("merge_node count-query with integer must parse and execute");

    assert!(
        !result.rows.is_empty(),
        "count query must return a row; got: {:?}",
        result.rows
    );
}

/// MATCH-only path (pre_existing > 0, set_parts empty):
///
/// When there are no extra properties to set, the MCP tool skips executing any
/// Cypher (a bare `MATCH` without `RETURN` is invalid).  This test verifies
/// that the pre-merge count path still works and the node remains readable.
#[test]
fn mcp_template_merge_node_match_only_path_node_unchanged() {
    let (_dir, db) = make_db();

    db.execute("CREATE (:Tenant {id: 'tenant-1', region: 'us-east'})")
        .expect("seed CREATE must succeed");

    // Pre-merge count query (what MCP runs to detect pre_existing).
    let count_query = "MATCH (n:Tenant {id: 'tenant-1'}) RETURN count(n)";
    let result = db
        .execute(count_query)
        .expect("pre-merge count query must parse and execute");
    assert!(
        !result.rows.is_empty(),
        "count query must return a row; got: {:?}",
        result.rows
    );

    // When set_parts is empty the MCP skips the MATCH execute entirely.
    // Verify the node is still readable (no silent corruption).
    let verify = db
        .execute("MATCH (n:Tenant {id: 'tenant-1'}) RETURN n.region")
        .expect("verify MATCH must succeed");
    assert_eq!(
        verify.rows.len(),
        1,
        "Tenant node must still exist unchanged; got: {:?}",
        verify.rows
    );
}

/// MATCH+SET path (pre_existing > 0, set_parts non-empty):
///
/// ```cypher
/// MATCH (n:{label} {{match_key: {cypher_match_val}}}) SET n.k1 = v1, n.k2 = v2
/// ```
#[test]
fn mcp_template_merge_node_match_set_path_parses_and_executes() {
    let (_dir, db) = make_db();

    db.execute("CREATE (:Account {account_id: 'acc-99'})")
        .expect("seed CREATE must succeed");

    // Mirrors: format!("MATCH (n:{label} {{{match_key}: {cypher_match_val}}}) SET {set_clause_inner}")
    // where set_clause_inner = "n.plan = 'pro', n.seats = 10"
    let label = "Account";
    let match_key = "account_id";
    let cypher_match_val = "'acc-99'";
    let set_clause_inner = "n.plan = 'pro', n.seats = 10";
    let query =
        format!("MATCH (n:{label} {{{match_key}: {cypher_match_val}}}) SET {set_clause_inner}",);

    db.execute(&query)
        .expect("merge_node MATCH+SET path must parse and execute");

    // Verify the properties were applied.
    let verify = db
        .execute("MATCH (n:Account {account_id: 'acc-99'}) RETURN n.plan")
        .expect("verify MATCH must succeed");
    assert_eq!(
        verify.rows.len(),
        1,
        "updated Account must be found; got: {:?}",
        verify.rows
    );
    let plan = verify.rows[0][0].to_string();
    assert!(
        plan.contains("pro"),
        "plan property must be 'pro' after SET; got: {plan}"
    );
}

/// CREATE path (pre_existing == 0) with all_props:
///
/// ```cypher
/// CREATE (n:{label} {{match_key: {cypher_match_val}, k1: v1}})
/// ```
#[test]
fn mcp_template_merge_node_create_path_parses_and_executes() {
    let (_dir, db) = make_db();

    // Mirrors: format!("CREATE (n:{label} {{{props_str}}})")
    // where props_str = "email: 'dan@example.com', name: 'Dan'"
    let label = "Contact";
    let props_str = "email: 'dan@example.com', name: 'Dan'";
    let query = format!("CREATE (n:{label} {{{props_str}}})");

    db.execute(&query)
        .expect("merge_node CREATE path must parse and execute");

    let verify = db
        .execute("MATCH (n:Contact {email: 'dan@example.com'}) RETURN n.name")
        .expect("verify MATCH must succeed");
    assert_eq!(
        verify.rows.len(),
        1,
        "Contact Dan must be retrievable; got: {:?}",
        verify.rows
    );
    let name = verify.rows[0][0].to_string();
    assert!(
        name.contains("Dan"),
        "name property must be 'Dan'; got: {name}"
    );
}

/// CREATE path with only the match key (no extra properties):
///
/// ```cypher
/// CREATE (n:{label} {{match_key: {cypher_match_val}}})
/// ```
#[test]
fn mcp_template_merge_node_create_path_match_key_only_parses_and_executes() {
    let (_dir, db) = make_db();

    // When properties is null/empty the MCP creates: {match_key: cypher_match_val}
    let label = "Tag";
    let props_str = "name: 'rust'";
    let query = format!("CREATE (n:{label} {{{props_str}}})");

    db.execute(&query)
        .expect("merge_node CREATE path (key-only) must parse and execute");
}

/// Escaped single-quote in match value — `escape_cypher_string("o'brien")` → `"o\\'brien"`.
/// Verifies that the escaping logic produces valid Cypher.
#[test]
fn mcp_template_add_property_escaped_match_val_parses_and_executes() {
    let (_dir, db) = make_db();

    // Apostrophe in value — mcp escapes as "o\'brien"
    db.execute("CREATE (:Person {name: \"o'brien\"})")
        .expect("seed with apostrophe in string must succeed");

    // escape_cypher_string("o'brien") → "o\\'brien"
    let label = "Person";
    let match_prop = "name";
    let match_val_escaped = r"o\'brien";
    let count_query = format!(
        "MATCH (n:{label} {{{match_prop}: '{match_val_escaped}'}}) RETURN count(n) AS cnt",
    );

    let result = db
        .execute(&count_query)
        .expect("count query with escaped apostrophe must parse and execute");

    assert!(
        !result.rows.is_empty(),
        "count query must return a row; got: {:?}",
        result.rows
    );
}
